### ISSUE TITLE
Change either "FAQs" or "FAQ" for page and navigation consistency

### ISSUE THREAD

**Issue by dcwalk** [ixmaps/website2017#10]

**Comment by dcwalk** [comment]
Addressed in https://github.com/ixmaps/website2017/commit/f594aad278bb4b6fbd663c7b499a64ff7cb18c99
@colinmccann can you pull to prod for testing?

**Comment by colinmccann** [comment]
Merged to prod, pulled to server

**Comment by dcwalk** [comment]
Okay this is working as expected, I didn't muck it up 😅
