### ISSUE TITLE
Home page  Status section - make live

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#12]
![pastedgraphic-9](https://cloud.githubusercontent.com/assets/12848029/23097928/12eea5de-f5f6-11e6-87eb-75876e73e753.png)

**Comment by Andrew-Clement** [comment]
Since this requires backend work, hold until Map page phase

**Comment by Andrew-Clement** [comment]
If this can't be easily fixed once Map is working, then we can simply drop it for now.

**Comment by agamba** [comment]
The stats on the home page are now live

**Comment by Andrew-Clement** [comment]
Good to see this. I believe this can be closed now.
