### ISSUE TITLE
Footer section  Make Last modified date live. 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#13]
![pastedgraphic-10](https://cloud.githubusercontent.com/assets/12848029/23097934/5364a258-f5f6-11e6-81be-ee122ae991a5.png)

**Comment by colinmccann** [comment]
Waiting until we hook up to the backend to do this properly

**Comment by Andrew-Clement** [comment]
OK, then this Last modified line should be removed until this is done, or how about:

            Last modified recently (site under active development)
