### ISSUE TITLE
Learn menu  Keep sub-menu visible after selecting an item ??

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#16]
![pastedgraphic-11](https://cloud.githubusercontent.com/assets/12848029/23097948/b1a2ed98-f5f6-11e6-83f2-a2eb43a81c61.png)
It disappears immediately once one of the options is selected

**Comment by colinmccann** [comment]
Yeah, but the selected option is in the hero header, very prominent. And this gives us some real estate back. I vote keep as is...

**Comment by Andrew-Clement** [comment]
OK, fine with me to leave as is. I see other sites adopt the same practice.     Let's see if we get any feedback from others on this during beta testing.
On 2017-02-20, at 12:48 AM, colinmccann <notifications@github.com> wrote:

Yeah, but the selected option is in the hero header, very prominent. And this gives us some real estate back. I vote keep as is...

**Comment by dcwalk** [comment]
Yeah I am with @colinmccann, I think this conforms to other website patterns. Closing for now and we can file new issues based on feedback
