### ISSUE TITLE
Issues page  Correct page title to 'Issues | Ixmaps'

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#17]
![pastedgraphic-1](https://cloud.githubusercontent.com/assets/12848029/23097951/cdffa166-f5f6-11e6-9653-060015107c5d.png)

**Comment by dcwalk** [comment]
Addressed by https://github.com/ixmaps/website2017/commit/07f16b54ee69294c21c228cad0ea4d9fc9feed8a, closing
