### ISSUE TITLE
Issues Header section.  Replace legacy meta text with briefer page intro:

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#18]
Replace legacy meta text with:

Where data travels across the internet, as well as who routes and has access to it along the way, raises privacy and other important issues. Below you can learn more about these concerns, and how IXmaps can help you understand them better. Highlighted phrases link to the corresponding item in the FAQ, Glossary and Resources pages.

**Comment by dcwalk** [comment]
Addressed in https://github.com/ixmaps/website2017/commit/0b10396a772877fec62d3244ccb192018d19b747, I made a slight copy edit for readability.
