### ISSUE TITLE
Links to FAQ items are broken

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#20]
![pastedgraphic-8](https://cloud.githubusercontent.com/assets/12848029/23097993/07cc1928-f5f8-11e6-82e6-b2020152304e.png)
![pastedgraphic-9](https://cloud.githubusercontent.com/assets/12848029/23097995/09b891e4-f5f8-11e6-9e68-1a3b2c392872.png)

**Comment by dcwalk** [comment]
This is covered by issue #10 below.

**Comment by dcwalk** [comment]
Closing as I've updated. Will leave the other issue open until confirmed working
