### ISSUE TITLE
Adjust 'How to use…' heading to match each corresponding issue

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#21]
All currently appear as 
![pastedgraphic-3](https://cloud.githubusercontent.com/assets/12848029/23098006/30186562-f5f8-11e6-898b-3434fee1cbc0.png)

**Comment by dcwalk** [comment]
Updated here: https://github.com/ixmaps/website2017/commit/5a7938476d3ceded0b3e0f82b12efd7bd524c7ec

Closing for now, please reopen an issue for any text adjustments
