### ISSUE TITLE
Revise FAQ entries in Issues to match FAQ page

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#22]
eg  for   Where can the NSA intercept your data en route?
6 v7 items, differnt wordings in some cases
![pastedgraphic-6](https://cloud.githubusercontent.com/assets/12848029/23098020/6a7dd6d8-f5f8-11e6-9263-3ec267cf141b.png)
![pastedgraphic-7](https://cloud.githubusercontent.com/assets/12848029/23098021/6c499ec0-f5f8-11e6-9787-10751ff1840f.png)

**Comment by dcwalk** [comment]
Addressed in https://github.com/ixmaps/website2017/commit/8f5f1a50202c119d44cbc66e9db4f13739356b10
