### ISSUE TITLE
News page  Create new 2017 section

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#26]
add 
Wire Report item ~ early Feb
Rabble post by D Christopher pending 
OpenMedia event Feb 22
other??

**Comment by dcwalk** [comment]
Can you provide links to these articles?

**Comment by colinmccann** [comment]
@Andrew-Clement

**Comment by dcwalk** [comment]
@Andrew-Clement Could you provide links to the new items that should be added?

**Comment by Andrew-Clement** [comment]
@Dawn, 2017 news items 

March 1, 2017 -- "Is your Internet data ending up in the NSA's hands?" (link= http://www.rabble.ca/columnists/2017-03-01t000000/your-internet-data-ending-nsas-hands ), David Christopher's Digital Freedom Update in _rabble.ca_ Also in _Common Ground_ (link= http://commonground.ca/internet-surveillance/ )

February 22, 2017 -- IXmaps research on boomerang routing and network sovereign presented at OpenMedia's Mapping your Digital Footprint https://openmedia.org/en/event-join-us-feb-22-learn-more-about-your-digital-footprint interactive documentary screening in Vancouver

January 30, 2017 -- "Trump raising concerns about Internet traffic passing U.S.: advocates" by Ahmad Hathout, _The Wire Report_ (link: http://www.thewirereport.ca/news/2017/01/30/trump-raising-concerns-about-internet-traffic-passing-us-advocates/31718 )

**Comment by dcwalk** [comment]
Addressed in https://github.com/ixmaps/website2017/commit/dbfc7028f9d62ab7a068eff0ad475bc75a55839c, closing
