### ISSUE TITLE
Map/explore -  Routers misplaced on map even with correct lat/long 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#31]
This is an old bug, but now an urgent one as it keeps popping up in TRs that I want to feature as examples of boomerang routing. 
 eg

Traceroute details: ID 6896 created on 2011-01-12 16:23:17-05	
Origin: Submitted by cdm from M5S3G6
Destination: osap.gov.on.ca [204.41.8.65]

![pastedgraphic-16](https://cloud.githubusercontent.com/assets/12848029/23108957/29763636-f6c9-11e6-89d2-50bfabbf5acc.png)

Traceroute details: ID 70360 created on 2014-12-18 01:52:16-05	
Origin: Submitted by lodeanto.raw from ixmaps-ser
Destination: osap.gov.on.ca [204.41.8.65]

![pastedgraphic-15](https://cloud.githubusercontent.com/assets/12848029/23108973/46c976f8-f6c9-11e6-90b7-cb97d9fa1b35.png)
![pastedgraphic-14](https://cloud.githubusercontent.com/assets/12848029/23108977/4f32c7d6-f6c9-11e6-874c-5f7adc1e0f0c.png)
![pastedgraphic-13](https://cloud.githubusercontent.com/assets/12848029/23108978/4f3b2b06-f6c9-11e6-9f3d-534305dbdf77.png)

**Comment by dcwalk** [comment]
Can we have issues for the legacy code in the other Website repo? I'm nervous to start putting them in here as I think it will tend toward confusion. Also, we'll wind up with lingering issues here that won't get closed easily...etc... because they will be uncoupled from where the work happens.

@colinmccann, thoughts?

**Comment by Andrew-Clement** [comment]
I understand the potential for confusion, but as this is a priority fix I wanted to make sure it got attention. If there is an easy way to comment on the old one that brings it to the surface then I'm fine with using the other repo.

**Comment by colinmccann** [comment]
Yup, this belongs on the other repo. Closing

**Comment by agamba** [comment]
This issue was ported to the new site and it's critical because it is produced when the map settings "show marker in origin" is used. Working on a fix quick fix for this.
