### ISSUE TITLE
Glossary - IP Address - Remove spurious naked URL 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#32]
IP Address
    An Internet Protocol address (IP address) is a numerical label assigned to each device communicating on a computer network. IP addresses are used for interface identification and location addressing. They are often displayed as a series of numbers separated by a “.” or “:” (e.g. the IP address for ixmaps.ca site is 128.100.72.189**# https://en.wikipedia.org/wiki/Latency_(engineering)#Packet-switched_networks)**. For more, see IP address.

**Comment by colinmccann** [comment]
done
