### ISSUE TITLE
Map - basic search Via criteria

### ISSUE THREAD

**Issue by colinmccann** [ixmaps/website2017#38]
I have been constructing a flow doc for the Map page (there is *a lot* that has not been spec'd out, still significant work to be done here), and was wondering about the Via/NSA criteria. What is meant to be entered in the text box?

<img width="639" alt="screen shot 2017-02-22 at 4 31 08 pm" src="https://cloud.githubusercontent.com/assets/754840/23205486/9a406d8c-f91c-11e6-9516-774db023fb16.png">

**Comment by Andrew-Clement** [comment]
At this point, I see this simply as a tick box

**Comment by colinmccann** [comment]
How do we feel about this functionality now? It's a little awkward, but keeps the UI intact

**Comment by colinmccann** [comment]
@Andrew-Clement

**Comment by Andrew-Clement** [comment]
Good. closing.
