### ISSUE TITLE
Missing navigation and header from 2013 transparency report

### ISSUE THREAD

**Issue by dcwalk** [ixmaps/website2017#39]
I think when adding the redirect a  bug was introduced on the transparency page --
The transparency header and global nav is missing, see:
https://github.com/ixmaps/website2017/commit/b5dba56508ed5807887ac11cadb3a74ddebcd616#diff-59c1ce27e8aeb6bc789c04a624b30613L12

We should reintroduce those elements of the page

**Comment by colinmccann** [comment]
Yeah, good catch - sloppy by me, there were some other errors that resulted as well
