### ISSUE TITLE
Add images to "Learn" sections once Map interface stabilizes

### ISSUE THREAD

**Issue by dcwalk** [ixmaps/website2017#4]

**Comment by Andrew-Clement** [comment]
There are a good number of images that don't refer to the pending Map page and will persist. Please include these where available.

**Comment by dcwalk** [comment]
Per my comment in #45 I need a direct link to these images, when I'm extracting from the doc the quality is not great. (excluing the interface ones)

**Comment by Andrew-Clement** [comment]
I beleive this is resolved and can be closed
