### ISSUE TITLE
Google Maps not working on Firefox

### ISSUE THREAD

**Issue by agamba** [ixmaps/website2017#43]
I just noticed that the map is not loading when accessed with Firerox

https://dev.ixmaps.ca/map.php

I wonder if this is a problem  with the gm key as the domain dev.ixmaps.ca might not be authorized to use the key.

Thoughts?

**Comment by Andrew-Clement** [comment]
This is what I see on my FF 48.0.2, which is the same as what I see with Safari Version 6.2.8 

The alert and  link to the old Explore page is missing. Should I see instead a map? 

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/12848029/23592204/454937a2-01b2-11e7-948f-7aecc86bedee.png)

**Comment by agamba** [comment]
I'm having the same behaviour in Firefox. The alert and link to the old Explore page is gone because we are now using the dev.ixmaps.ca to test the map integration. On first load, you should see a map with a marker in your current location. Chrome works fine, but I still presume that the issue with Firefox is related to the domain name registered in our google maps key. I'm testing this and will report asap.

**Comment by Andrew-Clement** [comment]
@agamba Can this be closed, or are there other browsers still giving trouble.?

**Comment by colinmccann** [comment]
Fixed in FF and Safari, closing
