### ISSUE TITLE
LEARN ISSUES Revisions 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#44]
@Dawn, Here are my proposed revisions (typo corrections >>, additional material and images) to incorporate in the beta version.

lmk if you have any questions.

A>

**Where on earth does your personal data travel?**

etc. …your  
REPLACE WITH
﻿etc., your

**How to Use Ixmaps to map data travel**                     

Go to the Map, where you will see **the traceroute** from nearest your location.
REPLACE WITH
Go to the Map, where you will see recent traceroutes from nearest your location.

REMOVE the video as it is obsolete and misleading

INSTEAD, REPLACE WITH these basic instructions and illustration :

To see other routes from near you:
<\begin indent>
Click in the **From** box, to show the menu choices
Select your **ISP, City** or **Country**, or a combination of these, entering the relevant information.
Click **Search**.
<\indent>

You will see mapped the most recent route that meets these conditions. On the right is the number of routes found and brief details about them. You can map these other routes by clicking on their TR ID number. Below the traceroute information, is the Carriers table with summary information about the various ISPs or carriers that handle the mapped route(s).
![pastedgraphic-6](https://cloud.githubusercontent.com/assets/12848029/23778294/5bd73d90-04ee-11e7-83ea-7d148f5cdb63.png)

**How to Use Ixmaps to map NSA interception**

The Map shows 18 U.S. cities where reported and suspected NSA interception facilities are located.
REPLACE WITH
The Map shows 18 U.S. cities where reported and suspected NSA interception facilities are located. These are indicated as    
![pastedgraphic-10](https://cloud.githubusercontent.com/assets/12848029/23778496/64105f9a-04ef-11e7-9180-f6eae3604cb7.png)

AT&T (e.g. program code-named Fairview) and Verizon (e.g. Stormbrew) click on the Layers button in the upper right and select their respective entries:
REPLACE WITH
AT&T (program code-named Fairview) and Verizon (Stormbrew), click on the Layers button in the upper right and select their respective entries:
![pastedgraphic-9](https://cloud.githubusercontent.com/assets/12848029/23778030/0731ccac-04ed-11e7-97ad-c9da233939bc.png)

**What is boomerang routing, and what does it mean for Canadian network sovereignty?**

**How to Use Ixmaps to map boomerang routing**

ADD this:

To see examples of boomerang routing,
<\begin indent>
In the **From** box, select your country
In the **To** box, select your country again
In  the **Via** box, select US or another third country.
Click **Search**
<\indent>

**Which ISPs can access your data and how privacy transparent are they?**

**How to Use Ixmaps to map ISP data access**

On the lower right of the <Map>, take a look at the **Carrier** table. It lists the ISPs or carriers that handle the data in the currently mapped traceroutes. The **Routers** column indicates the total number of routers for each carrier. The **Transparency** column shows the total number of stars we awarded them on our 10 criteria. Click on the carriers with star scores to learn more details or read our <Transparency> reports covering all the carriers we rated.

![pastedgraphic-5](https://cloud.githubusercontent.com/assets/12848029/23778165/86e47c06-04ed-11e7-9dbd-aff3939b2da2.png)

**Comment by dcwalk** [comment]
I've made these changes excepting the NSA icon. We removed all the other icon signposting and the image directly below has it in it, I'm hoping that will be sufficient?
