### ISSUE TITLE
LEARN FAQ

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#45]
Hi @Dawn,

Here are my proposed revisions to the FAQs. Mainly this is simply pulling in the images from the Gdoc https://docs.google.com/document/d/1gaCWIHNT8h_0uz2hue9WpUj6-LChqDCqgFJV8E7vJ8Y/edit#heading=h.xu81snklszk    

**Where on earth does your personal data travel?

Where are the main internet exchanges in North America?**

Pull images from Gdoc                

Add image and link to video 

**How does IXmaps locate routers geographically and map them?**

 For example, looking into the Technical details of traceroute 6896 shown above, we can see

REPLACE WITH 
 For example, looking into the Technical details of traceroute 6896, we can see

**NSA Surveillance**

**How does IXmaps know where the NSA can intercept my data?**

Pull images from Gdoc 
                   
**Boomerang Routing and Canadian Network Sovereignty

Why does your data boomerang through the US?**
Pull image from Gdoc 
  

**Why is network sovereignty important to Canadians?**
Pull image from Gdoc 
Include source

**Comment by dcwalk** [comment]
@Andrew-Clement I need access to higher quality versions of the images than those I can extract from the gdoc. Can you link me to the source for these images or upload them in the drive? (Especially the door image is blurry when extracted)

**Comment by dcwalk** [comment]
Also, @Andrew-Clement what is the source/credit that should be added to these images?

**Comment by Andrew-Clement** [comment]
OK,

Does these URLs provide you with enough for the image and its a source? Some may need cropping.

611 Folsom Street
http://www.enews.org/blog/2007/11/room-641a-at-complicity-in-bushs.html 

350 Cermak
https://www.google.ca/url?sa=i&rct=j&q=&esrc=s&source=imgres&cd=&cad=rja&uact=8&ved=0ahUKEwj9p5q_ntLSAhVL7GMKHR2VBvYQjRwIBw&url=https%3A%2F%2Fwww.colocationamerica.com%2Fdata-center-locations%2Fchicago.htm&psig=AFQjCNFRE4anRkFdE5LUAs6gU_aHYZtl0Q&ust=1489451800690566 

151 Front Street, Toronto
https://www.google.ca/url?sa=i&rct=j&q=&esrc=s&source=imgres&cd=&cad=rja&uact=8&ved=0ahUKEwi3zMeMn9LSAhUN32MKHcUsAgoQjRwIBw&url=http%3A%2F%2Fwww.151frontstreet.com%2F&psig=AFQjCNHic5Iqz41RccqKLnrr0heHU_k-Ag&ust=1489451966189893 

33 Thomas Street, Titanpointe
https://thenypost.files.wordpress.com/2016/11/110404_att_building_jcrice-4.jpg?quality=90&strip=all&strip=all 

NSA SIGINT  platform
http://edwardsnowden.com/wp-content/uploads/2013/11/nsa1024.jpg 

611 FOlsom
Screen grab from current IXmaps site/video

Room 641A
https://en.wikipedia.org/wiki/File:Room_641A_exterior.jpg 

CIRA ISP table
Bill Woodcock, 2016. Results of the 2016 PCH / CIRA Study on Canadian Network Interconnection, presentation at Canadian ISP Summit, November 8, 2016  https://cira.ca/sites/default/files/public/Canadian%20Peering%202016.pdf  PAGE 25  **(Note the URL in this item in the Supporting links section is mangled and needs fixing)**
Telegeography, Submarine Cable Map http://www.submarinecablemap.com

**Comment by dcwalk** [comment]
This has been addressed in https://github.com/ixmaps/website2017/pull/52/commits/ebfc11fb811876e315aa690d875c5f54872e9140, but I have some questions in #53 RE: code
