### ISSUE TITLE
MAP HELP text 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#49]
The Help button needs to be activated. 

Here is provisional text to use for the Help screen:
________
If you're getting started, it's easiest to begin with some of our canned queries in the **Quick** search section - see tab on far left. If you've just generated a route, you'll be able to find it easily by clicking on the '**Last Contributed**' button. The 4 rightmost **Quick** buttons use the location and ISP information provided on your first visit this session to the Map page.

On the right, you'll see a report on the number of routes in the database that meet the criteria you specified, i.e. **Routes Found**. While the search is performed on the entire IXmaps database, due to computational and bandwidth limitations the server only returns a sample of at most 20 results to display. These are listed in the **_Traceroute_** table. Run your cursor over the traceroute IDs (**TR ID**) in the right hand column to view each route. (You may have to zoom out/in to see routes that are not visible in the current viewing window) Select any route number to make it 'stick' on the map. The **dots** represent routers and **lines** the hops between them. The colours correspond to the ISP/carriers owning the routers, with a list of all that handle the currently displayed routers appearing in the **_Carrier_** table in the lower right corner. Selecting (clicking on) a dot reveals who owns the router and where it likely is.  Selecting a line reveals more details about the route and each router along the way. You may find the apparent location of a router suspicious. The **Flag router** link in both the router and traceroute details pop-ups provide an opportunity register your suspicion and indicate a more accurate alternate position.

To see how many search results each individual query line produced, click on '**Search results details**' immediately above the Carrier table. This can be helpful in deciding on a next search, especially if no results are found or there are too many.

If you do not find the route(s) you were looking for, to go to either the **Basic** or **Advanced** tab where you can add filter constraints (e.g. add a **Goes via <city>** or **<country>** criterion).

To help in refining your search and formulating your own queries in the Basic and Advanced search sections, you'll find immediately below the Quick buttons the corresponding **Search Query** equivalent. This gives an indication of the syntax to use.

**Basic** search provides an easy way to formulate the most common custom queries. Click on the FROM, VIA or TO boxes, entering the criteria for routes you are interested in, and then click Search 

**Advanced** search is intended for those with more experience in querying databases and interested in in-depth exploration of the IXmaps traceroute data.  There are more items to search on and you can add more criteria.

To adjust how selected routes are displayed, click on **Settings**, just below the Help button,  and click on the various buttons. Blue indicates the option is ON. 

To be able to display more than one route at a time, turn **Multiple TRs** ON.  Then as you select TR IDs in the Carriers section, the previously displayed ones won't be removed. This also enables you to display all the currently listed traceroutes with the **Map All** button, immediately above the TR ID column. 

To add layers of informational icons to the map, such as the sites of NSA surveillance outside the US, public internet exchange points in Canada, Google data centres, etc. click on the **Layers** button at the top right of the map, and make your selections. Clicking again turns the layer off.

If this didn't help out, let us know what you were seeking help about by dropping us line at IXmaps@utoronto.ca and we'll try to answer. This will also assist us in revising the Help page so it will be more helpful to future users.

**Comment by Andrew-Clement** [comment]
Thanks @colinmccann 

Once the tooltips for the Map page are working, you can replace the current wall of text with this streamlined version.

>>>>>>>>

If you're getting started, it's easiest to begin with some of our canned queries in the Quick search section - see tab on far left. If you've just generated a route, you'll be able to find it easily by clicking on the 'Last Contributed' button. The 4 rightmost Quick buttons use the location and ISP information provided on your first visit this session to the Map page.

If you do not find the route(s) you were looking for, to go to either the Basic or Advanced tab where you can add filter constraints.

If routes are reported found but none appear on the map, it may help to zoom out, or on the rare occasion of very short routes, to zoom in on the city of origin. 

You can explore the various features of this page using your mouse. Hover over the various items to see brief explanations.


If this didn't help out, drop us line at IXmaps@utoronto.ca and we'll try to answer. This will also assist us in revising the site so it will be more helpful to future users.

**Comment by colinmccann** [comment]
K, changed and closed. Note that we seem to be using several different email addresses across the site (the faq page has a different one). Can we standardize? On which one?

**Comment by Andrew-Clement** [comment]
Thanks.

I recall that we had a repo for the various text items on the website, but can't find it after looking at the directories and README.  Please point me to it and I'll put this text in it.

Good call on the multiple email addresses. It should be: "ixmaps@utoronto.ca" which forwards to me. I can't see how to access mail to "ixmaps@ischool.utoronto.ca"
