### ISSUE TITLE
Redirect "/transparency" to most current transparency report

### ISSUE THREAD

**Issue by dcwalk** [ixmaps/website2017#5]
My sense is this might be best handled via apache?

**Comment by colinmccann** [comment]
Huh, doing it with Apache is interesting.

But adding to this, there are a tonne of references to https://www.ixmaps.ca/transparency.php (and eg https://www.ixmaps.ca/transparency.php#fn8-inline) scattered throughout the code - needs cleanup at some point

**Comment by dcwalk** [comment]
I don't see `https://www.ixmaps.ca/transparency.php` in the code right now ([link](https://github.com/jknee/IXmaps/search?q=transparency.php&type=Code&utf8=%E2%9C%93)), I think you caught them? 🎉

**Comment by colinmccann** [comment]
I think I got them all - but that's a temp fix, since we should still deal with the core issue of 'redirect to most recent year'

**Comment by colinmccann** [comment]
Thinking about this more, I think we should just let it be - no need to get too cute. Just manual update with find/replace every couple of years. Not pretty, but uncomplex. Thoughts?

**Comment by dcwalk** [comment]
Your call, but it seems valuable to have people click "transparency" and have the browser bar reflect that with "transparency" shown vs. transparency-201X. Also, when updating with a new report you will have to change one place rather than multiple, which reduces the chances of missing a bit.

**Comment by Andrew-Clement** [comment]
Yes, I lean to Dawn on this. Minimizing the number of things to change annually will be safer.

**Comment by colinmccann** [comment]
Ok, fair - let's keep this open at a lower priority

**Comment by colinmccann** [comment]
Ok, I have addressed this. transparency.php will show the most recent report. See commit b5dba56508ed5807887ac11cadb3a74ddebcd616
