### ISSUE TITLE
MAP SEARCH BUG - Legit search results not found

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#50]
A search for routes terminating in Destination hostname bccla.org finds only one route - 107356
However route 236064 has the same destination but doesn't get found.  There are likely other TRs with the same destination as it is in a TRset.

Same problem in old Explore.  
![pastedgraphic-13](https://cloud.githubusercontent.com/assets/12848029/23977669/af9c552e-09ac-11e7-872d-8a366a057881.png)
![pastedgraphic-14](https://cloud.githubusercontent.com/assets/12848029/23977672/b53aeeb4-09ac-11e7-801d-27f9cdc21422.png)

I file this issue here as I presume this is (or will be shortly) the only active repo for the website. LMK if there is a better place for such issues.

**Comment by agamba** [comment]
I've fixed some issues with the destination search in Basic Search.
Note that the proper way of building this type of query in the advance search is not with "terminate" but with "contain", e.g. **does : contain : destHostName : bccla.org : AND**

<img width="978" alt="screen shot 2017-03-15 at 11 08 06 pm" src="https://cloud.githubusercontent.com/assets/999407/23980169/8b0fb124-09d4-11e7-861f-204f73c47044.png">

**Comment by Andrew-Clement** [comment]
OK, good. This points to a semantic ambiguity around Terminate and To: which we'll need to deal with later. 

Need to re-open.
