### ISSUE TITLE
Map Page: Basic Search: Ambiguous criteria NSA 

### ISSUE THREAD

**Issue by agamba** [ixmaps/website2017#51]
I've temporary removed the filter option NSA, as it's not clear what should be included in this field.

All the other filter options should now be working properly

![screen shot 2017-03-15 at 8 14 02 pm](https://cloud.githubusercontent.com/assets/999407/23980075/d52eb31e-09d3-11e7-9d39-001c17be5d13.jpg)

**Comment by Andrew-Clement** [comment]
Please keep it! This has been a prominent and important feature of IXMaps the beginning.  It is a Yes/No choice. This can be indicated in the greyed text.

**Comment by colinmccann** [comment]
I've put in a bandaid here - it's pretty clunky, imo, but it's functional. Warning, it's very very slow (since it's querying so many cities...)
