### ISSUE TITLE
Semantic grid not working in accordian?

### ISSUE THREAD

**Issue by dcwalk** [ixmaps/website2017#53]
I'm not too sure how to continue to troubleshoot -- the Semantic UI grid classes aren't rendering properly in the FAQ page, super unfamiliar with this framework so thought I'd throw it up as this is probably an easy fix for @colinmccann ?

See this commit: https://github.com/ixmaps/website2017/commit/599f5062b5435a3d9b39252eef6ee516859f34f6

![screen shot 2017-03-16 at 1 54 07 pm](https://cloud.githubusercontent.com/assets/4692834/24011159/598271a6-0a50-11e7-846f-48971d4c9ba3.png)

**Comment by Andrew-Clement** [comment]
I've asked Jennette to help out on this and #54

**Comment by dcwalk** [comment]
resolved without using semantic ui, closing as not needed
