### ISSUE TITLE
Switch youtube iframes to semantic ui video?

### ISSUE THREAD

**Issue by dcwalk** [ixmaps/website2017#54]
I'm not sure the best way to handle the videos we have embedded -- it looks like we have the semantic ui video module (http://1.semantic-ui.com/modules/video.html)

But when I try to use I'm getting... 
> Uncaught TypeError: $(...).video is not a function
    at faq.php:392

Again, could troubleshoot but I think someone with more familiarity with our css/scss setup ( @colinmccann) could just confirm quickly whether this is the best implementation.

**Comment by colinmccann** [comment]
I have today officially determined I am *not* the person with an understanding of the css/scss setup. Ditto with library includes. I headbanged a lot on this stuff today, only got it working in the most roundabout way. We desperately need to get a better handle on this...

**Comment by dcwalk** [comment]
This was addressed via using `embed` vs `video`, closing at no longer needed
