### ISSUE TITLE
MAP Opening modal search should (almost) never return No routes found

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#56]
From my apparent location, I get a **No routes found** message. The only time this should occur is when someone visits from a country and an ISP that doesn't appear in the DB. 

The wording of the alert should reflect this fact. (see #57 for suggested wording)

In my case, it should find many routes originating in CA from Shaw.

**Comment by colinmccann** [comment]
This should now be resolve - plz test and close if satisfied

**Comment by Andrew-Clement** [comment]
Well, better, but still needs work.

Modal alert is easier to read, but needs re-wording:

Add the sentence "Showing latest route contributed."

![pastedgraphic-33](https://cloud.githubusercontent.com/assets/12848029/24052196 /d81e99da-0af1-11e7-88ec-20404d955bed.png)

And AS discussed, the logic needs revising, to provide for more nuanced search results. (hold off until after feedback)

**Comment by Andrew-Clement** [comment]
Superceded by new modal design
