### ISSUE TITLE
MAP- revising the No routes found modal wordings

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#57]
There are two distinct occasions when when a search finds no routes. Accordingly, they should produce distinct messages:

**Upon (first) entry to the Map page:**
![pastedgraphic-25](https://cloud.githubusercontent.com/assets/12848029/24019398/0c506032-0a55-11e7-8c14-f4265a0a0df1.png)

As noted in #56 it should be very rare for there to be nothing found. (However, hopefully we'll keep getting first time users from new countries and ISPs) 

ACTION:
Show the most recently contributed route 

PROPOSED WORDING >>>>
There are not yet any routes in the IXmaps from either your country or ISP. You can be the first to add some by going to the Contribute page, where you'll find instructions on generating traceroutes. 

In the meantime, we show here the most recently contributed route. 

You can see routes from other countries using the **From** menu in BASIC search

<<<<<<

**Upon submitting a search that yields no results** 

This is the much more usual case.  

ACTION:
Clear the map of any previous routes displayed, but leave any search terms that may have been provided.

PROPOSED WORDING >>>>

No routes were found with the criteria you provided. Adjust the query options to be more inclusive, then click **Search** to re-query.

<<<<<<

ENHANCE APPEARANCE

This modal, and the Flagging confirmation one, are a little hard to read. Enlarge the text font and increase the contrast between the text and the background.

Hold the first modal on screen for a little longer as it has more text.

**Comment by colinmccann** [comment]
Again, I've done the easy part of this - the second part.
To differentiate between the two different types of 'no routes returned' will be more tricky. TODO for later, I guess

**Comment by Andrew-Clement** [comment]
Superceded by new modal design
