### ISSUE TITLE
Banners for Beta testing phase

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#61]
@colinmccann @agamba 
Could one of you add a banner to all the **dev site** pages that reads:

> Please try out this beta version of the re-designed the IXmaps website and give us [feedback](https://ixmaps.typeform.com/to/m0kB8X)!

On the **old site**, add a banner to all the pages that reads:

> Please try out the [beta version ](https://dev.ixmaps.ca/) of the re-designed the IXmaps website. We welcome your feedback!

These banners should be in the style of the one on the Explore page, which can now be removed.

![pastedgraphic-31](https://cloud.githubusercontent.com/assets/12848029/24026247/f96fd736-0a7c-11e7-86d5-924d7aceae63.png)

**Comment by colinmccann** [comment]
I have added the banner to the Explore page (not on every single page, but the important ones).

I suggest we rethink using the old styling to add a banner to the pages on the new site - I think it changes the look / feel of the site enough that it will affect testing. Maybe a less obtrusive announcement somewhere? Suggestions?

**Comment by Andrew-Clement** [comment]
I don't see any banners on the dev site. 

I don't think the styling is that far out to be a problem in the short term. Ditto for being a little  obtrusive.

On the Explore page, drop the location accuracy banner

**Comment by Andrew-Clement** [comment]
For the current dev site, please 
This is a beta version of the re-designed the IXmaps website. We welcome your [feedback!](https://ixmaps.typeform.com/to/m0kB8X)

**Comment by colinmccann** [comment]
addressed with 98477381f7a9677ebe0d09a9636033929df3d537

**Comment by dcwalk** [comment]
I agree about the old styling feeling out of place -- I thought a site-wide announcement functionality was going to be added?

**Comment by Andrew-Clement** [comment]
In the blank area beside the logo is a good place for this message, but I agree the old styling does feel a little out of place. 

Picking up the black background square cornered rectangular text areas in various parts of the site, how about this:
![pastedgraphic-16](https://cloud.githubusercontent.com/assets/12848029/24334450/57f54d6e-121f-11e7-986c-8073f37fe27e.png)

The box size, text size, margins and font will likely need to be adjusted.
