### ISSUE TITLE
CONTRIBUTE - Make Download link more prominent

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#68]
Insert a prominent DOWNLOAD button at the beginning of each of the three main sections, that links to corresponding version of the IXmapsClient. eg 

Windows
This version of the software runs on Windows 7, Windows 8 and Windows 10.

    
![pastedgraphic-4](https://cloud.githubusercontent.com/assets/12848029/24326736/44738d8a-1172-11e7-9f64-e8ac4a8897cc.png) Download the IXmapsClient installer IXmapsClient.1.0.6.win64.exe

(The button can be a bit smaller than appears here)

**Comment by colinmccann** [comment]
added in a8f45daeb71be7405b341ca0d63ab6124a162387
