### ISSUE TITLE
MAP - No routes found shouldn't then display last route displayed

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#69]
It is confusing after being presented with the "No routes found...' message to then be presented without explanation the latest route added.

Better would simply  do no further search and leave the righthand panel in place saying:
 **0** Traceroutes Found
and open the Search results details to make it easier to tell what happened and help in adjusting the query options as advised.

![pastedgraphic-13](https://cloud.githubusercontent.com/assets/12848029/24328211/71c2e896-1198-11e7-94e5-8fce91805dc0.png)

**Comment by agamba** [comment]
This is working,  but note that it has a delay of 10 seconds.

**Comment by Andrew-Clement** [comment]
This is not what I meant.  

What I mean is that if the search doesn't produce any results, simply report this. Don't then after 10 secs find the latest route added.

**Comment by agamba** [comment]
OK

**Comment by agamba** [comment]
This should not occur after fixes to #76 
Consider merging issues

**Comment by Andrew-Clement** [comment]
No, this is not exactly what I meant.

1.  I see that if no routes are found in the modal the MAP ROUTES FOUND button is not responsive, but this is very confusing. AS mentioned in #74, when this button is not operative, it shouldn't appear as a link  (little hand with pointing finger icon) and it should be visibly greyed out to convey this. 

2. "No routes found " is a more general phenomenon - it  can also occur for basic and advanced search on the Map page itself. In these cases, don't do a search for the latest route. Simply provide the alert and show in the right hand panel what I mention above.

**Comment by Andrew-Clement** [comment]
Appears fixed. Thanks Anto.
