### ISSUE TITLE
restructure of php files?

### ISSUE THREAD

**Issue by colinmccann** [ixmaps/website2017#7]
Dawn, what do you think of the current structure of the pages/directories. It kinda hurts my brain that we are mostly flat (eg with index, map, contribute, etc at the root) and then have subdirs for some of the content. Thoughts?

**Comment by dcwalk** [comment]
I thought it was done to reflect the secondary navigation/content areas and box out snippets to `_includes`.

All I'm seeing that is sub dir is:
- transparency
- learn
Which both have secondary navigation on the page. By nesting we also have the urls reflect the navigation.

I think this structure is preferred and reflects other projects.

I'm not used to having _assets packed the way they are but seems to make sense.

**Comment by colinmccann** [comment]
K, fair - it's harming my ocd, but I suppose it's correct :)
