### ISSUE TITLE
MAP Quick button - Last Contributed should find most recent 20 routes

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#71]
Currently it only finds the  most recent one. Better to get last 20. As usual it would then display the single most recent of these. 

![pastedgraphic-17](https://cloud.githubusercontent.com/assets/12848029/24335412/ad97c55a-1231-11e7-938d-27e464180c27.png)

**Comment by colinmccann** [comment]
This is actually a backend thing (since there is currently no way query by date). So, switching assignations

**Comment by agamba** [comment]
fixed, closing now
