### ISSUE TITLE
MAP TRdetails icons missing

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#75]
Didn't make the transfer? 
![pastedgraphic-19](https://cloud.githubusercontent.com/assets/12848029/24368319/d1a4ab9a-12d4-11e7-819a-36a4bf21bc0a.png)

**Comment by agamba** [comment]
These images are not part of the new design and where not moved. I'm adding a temporary solution while we fully re-implement TR-details page

**Comment by agamba** [comment]
the missing icons for non US or CA countries is and old issue we will no longer have to deal with in the new design. Closing now.
