### ISSUE TITLE
Add deployment instructions to README

### ISSUE THREAD

**Issue by dcwalk** [ixmaps/website2017#8]
Can we make clear where and how changes should be submitted?

e.g. My understanding is that I should be committing to `master` and that gets pulled to `prod` for deployment?

**Comment by dcwalk** [comment]
@colinmccann I moved the [README](https://github.com/ixmaps/website2017/blob/master/README.md) from build with development environment instructions. Can we add the dev process you outlined?

**Comment by colinmccann** [comment]
Thanks for setting up the README - great to get this stuff down. I've updated with basic commit instructions, modify as you see fit.

**Comment by Andrew-Clement** [comment]
I'm delighted to see this. A small but important feature in attracting potential OSS collaborators to say nothing of funding prospects. Also reassuring to me personally, even if I don't understand all the details (eg 'grunt'?)


On 2017-02-19, at 3:01 PM, dcwalk <notifications@github.com> wrote:

@colinmccann I moved the README from build with development environment instructions. Can we add the dev process you outlined?
