### ISSUE TITLE
Various broken links 

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#85]
On 2017-04-10, at 8:28 PM, user890234@tutanota.com wrote:

> I  thought I'd let you know the website has some dead links. When you click traceroute details, the links at the top go to an outdated FAQ link. For instance, https://ixmaps.ca/faq.php#Hostname which gives a 404. And the #Hostname no longer exists even on https://ixmaps.ca/learn/faq.php (or it doesn't work for me at least, but I have some addons.) 

> Also in the faq, there's a link to https://ixmaps.ca/docs/2011-06-09-ixmaps-geolocation.pdf under the "How does IXmaps locate routers geographically and map them? " question that gives a 404.

**Comment by colinmccann** [comment]
The first of these required a change to the cgi-bin files - it's no longer broken, but very ugly. This whole issue will go away when we rewrite tr-details...

Second half fixed with cf9f1648a6ebefdadf3f1854ccd9e95140058097
