### ISSUE TITLE
MAP TRdetails inconcsistnet hostname  IXmaps.ca  vs IXmaps

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website2017#92]
![pastedgraphic-23](https://cloud.githubusercontent.com/assets/12848029/25723849/8ab452a4-30ce-11e7-99c3-1505fbd57da7.png)
![pastedgraphic-24](https://cloud.githubusercontent.com/assets/12848029/25723852/8da87ddc-30ce-11e7-9d80-981c17cff3c8.png)

**Comment by agamba** [comment]
hostname lookup for ixmaps' ip gives "ixmaps" and not "ixmaps.ca".
Tested here:
https://ixmaps.ca/application/controller/ixmapsMaxMind.php?ip=128.100.72.189

And also here: http://whatismyipaddress.com/ip-hostname

I think this needs to be changed in apache configuration?

**Comment by colinmccann** [comment]
Anto is correct - was an apache issue.

I have altered the apache config for a different issue, which closes this
